services:
  app:
     build: .
     ports:
      - "3000:3000"
     networks:
      - monitoring-network 
     environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - PORT=3000
     volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules


  prometheus:
    image: prom/prometheus:v2.37.0
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
     - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    networks:
      - monitoring-network
    depends_on:
      - app
    
  alertmanager:
   image: prom/alertmanager
   ports:
    - "9093:9093"
   volumes:
    - ./monitoring/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
   networks:
    - monitoring-network
   depends_on:
    - prometheus

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring-network 
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring-network:
    driver: bridge