global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'null-receiver'

receivers:
- name: 'null-receiver'
  webhook_configs:
  - url: 'http://webhook.example.com'  # Valid URL (even if dummy)
    send_resolved: true