global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1m

receivers:
- name: 'default-receiver'
  webhook_configs:
  - url: 'http://localhost:9093/api/v1/alerts'
    send_resolved: true